# Introduction to Python

## Learning Objectives

- Setup and install Python and Jupyter Lab
- Write basic Python code and understand fundamental programming concepts
- Load and analyze data using Python libraries and functions
- Wrangle real-world datasets
- Create clear visualizations with `Matplotlib` and `Seaborn`
- Train a simple machine learning model using `scikit-learn`

## Installations

Download the most recent version of the **Graphical Installer** of Anaconda, Anaconda Navigator, for the appropriate operating system of your computer using the link below:

- [Anaconda](https://www.anaconda.com/download/success)

Once downloaded, run the installer and follow the prompts to complete the installation. The **default settings** should work for most users, but you can customize the installation if needed. This will install a new program called Anaconda Navigator.

## Lessons

- [Introduction to Python and Jupyter Lab](../lessons/01_setting_up.qmd)
- [Variables](../lessons/02_variables.qmd)
- [Conditional Statements](../lessons/03_conditional_statements.qmd)
- [Data Structures](../lessons/04_data_structures.qmd)
- [Loops](../lessons/05_loops.qmd)
- [Functions](../lessons/06_functions.qmd)
- [Libraries](../lessons/07_libraries.qmd)
- [Numpy Arrays](../lessons/08_numpy_arrays.qmd)
- [Pandas DataFrames](../lessons/09_pandas_dataframes.qmd)
- [Data Wrangling](../lessons/10_data_wrangling.qmd)
- [Plotting Basics](../lessons/11_plotting_basics.qmd)
- [Boxplots](../lessons/12_boxplots.qmd)
- [Machine Learning - Random Forest](../lessons/13_machine_learning.qmd)


## Resources

- [Additional Resource 1](link_to_additonal_resource_1)
- [Additional Resource 2](link_to_additonal_resource_2)
- [Additional Resource 3](link_to_additonal_resource_3)