---
title: "Introduction to Python"
sidebar: false
toc: false
---


| Audience | Computational skills required| Duration |
:----------|:----------|:----------|
| Biologists | None | 4-session workshop (8 hours of trainer-led time)|

### Description

This repository has teaching materials for a hands-on **Introduction to Python** workshop. This workshop will take you from installing Python and writing your first lines of code, to working with real-world data and end with producing visualizations. The focus is on practical skills and applications, with exercises and examples drawn from the life sciences. 

We will cover the basics of Python programming, including data types, functions, and how to use popular libraries such as `NumPy`, `pandas` and `Matplotlib`. The goal is to give you a solid foundation in Python programming that you can build upon for your own projects. No prior programming experience is required. By the end, you should feel comfortable reading and writing basic Python code, loading and wrangling data and generating custom visualizations.


::: callout-note
# Note for trainers
Please note that the schedule linked below assumes that learners will spend between 3-5 hours on reading through and completing exercises from selected lessons between classes. The in-class component of the workshop focuses on more exercises and discussion/Q & A.
:::

### Learning Objectives

In this workshop, the participants will:

- Setup and install Python and Jupyter Lab
- Write basic Python code and understand fundamental programming concepts
- Load and analyze data using Python libraries and functions
- Wrangle real-world datasets
- Create clear visualizations with `Matplotlib` and `Seaborn`

### Lessons
These materials were developed for a trainer-led workshop, but are also amenable to self-guided learning.

- [Workshop schedule (trainer-led learning)](schedule/schedule.qmd)
- [Self-learning](schedule/self-learning.qmd)


### Installation Requirements

Download the most recent version of the **Graphical Installer** of Anaconda, Anaconda Navigator, for the appropriate operating system of your computer using the link below:

- [Anaconda](https://www.anaconda.com/download/success)

Once downloaded, run the installer and follow the prompts to complete the installation. The **default settings** should work for most users, but you can customize the installation if needed. This will install a new program called Anaconda Navigator.