---
title: "Data Wrangling - Answer Key"
author:
  - Noor Sohail
  - Will Gammerdinger
date: "2026-03-15"
license: "CC-BY-4.0"
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
#| label: load_libraries_data
#| echo: false
# Load libraries and data
# Interfacing with R quarto and python futzing
library(reticulate)
use_condaenv("/opt/anaconda3/envs/intro_python", required = TRUE)
```


```{python}
#| label: load_libraries_data_python
#| echo: false
# Load libraries and data
import pandas as pd
rpkm_data = pd.read_csv("data/counts.rpkm.csv")
metadata = pd.read_csv("data/mouse_exp_design.csv")

rpkm_ordered = rpkm_data.reindex(columns=metadata.index)
```

# Exercise 1

We have a list of 6 marker genes that we are very interested in. Our goal is to extract count data for these genes using the `in` operator from the `rpkm_ordered` data frame, instead of scrolling through `rpkm_ordered` and finding them manually.

First, let's create a vector called `important_genes` with the Ensembl IDs of the 6 genes we are interested in:

```{python}
#| label: create_important_genes
# Create important genes vector
important_genes = ["ENSMUSG00000083700", "ENSMUSG00000080990", 
                   "ENSMUSG00000065619", "ENSMUSG00000047945", 
                   "ENSMUSG00000081010", "ENSMUSG00000030970"]
```

1. Use the `isin` operator to determine which row names of the `rpkm_ordered` DataFrame match our genes of interest.

```{python}
#| label: exercise_1
# Check if important genes are in rpkm_ordered
rpkm_ordered.index.isin(important_genes)
``` 

2. Extract the rows from `rpkm_ordered` that correspond to these 6 genes using `[]` and the `isin` operator. Double check the row names to ensure that you are extracting the correct rows.

```{python}
#| label: exercise_2
# Extract rows for important genes
rpkm_ordered[rpkm_ordered.index.isin(important_genes)]
``` 

3. **Bonus question:** Extract the rows from `rpkm_ordered` that correspond to these 6 genes using `[]`, but without using the `isin` operator.  Do you notice anything different about the output?

```{python}
#| label: exercise_3
# Extract rows for important genes without using isin operator
rpkm_ordered.loc[important_genes]
```

The rows are now in the order that we specified the genes of interest. When we used `isin` above, we got the rows in the order that they are present in the expression data.

# Exercise 2

### Reading in and inspecting data

1. Using the `animals.csv` within your `data` directory, read the `.csv` file into your environment and assign it to a variable called `animals`. **Be sure to check that your row names are the different animals.**

```{python}
#| label: read_in_animals_csv
# Read in animals.csv
animals = pd.read_csv("data/animals.csv")

# Print animals
animals
```

2. Check to make sure that `animals` is a dataframe.

```{python}
#| label: class_animals
# Check the class of animals
type(animals)
```

3. How many rows are in the `animals` dataframe? How many columns?

```{python}
#| label: dim_animals
# Number of rows in animals
len(animals.index)

# Number of columns in animals
len(animals.columns)

# Shape of animals
animals.shape
```

### Data wrangling

4. Extract the `speed` value of 40 km/h from the `animals` dataframe.

```{python}
#| label: extract_first_row_first_column
# Various methods to extract the speed value of 40 km/h
print(animals.iloc[0, 0])
animals[animals["speed"] == 40]["speed"]
animals["speed"].loc[animals["speed"] == 40]
```

5. Return the rows with animals that are the `color` Tan.

```{python}
#| label: rows_with_color_tan
# Two way to return the rows with the animal color as Tan
animals[animals["color"] == "Tan"]
animals.loc[animals["color"] == "Tan"]
```

6. Return the rows with animals that have speed greater than 50 km/h and output only the color column. Keep the output as a DataFrame.

```{python}
#| label: speed_column_tan
# Return the color column for animals with speed > 50 as a DataFrame
animals[animals["speed"] > 50]["color"].to_frame()
```

7. Change the color of "Grey" to "Gray". 

```{python}
#| label: change_grey_to_gray
# Two ways to change Grey to Gray
animals["color"][animals["color"] == "Grey"] = "Gray"
animals.loc[animals["color"] == "Grey", "color"] = "Gray"
animals
```

8. Create a list called `animals_list` in which the first element contains the speed column of the `animals` dataframe and the second element contains the color column of the `animals` dataframe. 

```{python}
#| label: create_list
# Create a list with the speed and color vectors
animals_list = [animals["speed"], animals["color"]]
animals_list
```

9. Create a dictionary with the appropriate keys (i.e., speed and color).

```{python}
#| label: create_dict
# Create a dictionary with the speed and color vectors
animals_dict = {"speed": animals["speed"], 
                "color": animals["color"]}
animals_dict
```

### The `isin` operator, reordering and matching

10. In the `data` directory, you should have a table called `project-summary.txt` that contains quality metric information for an RNA-seq dataset. We have obtained batch information for the control samples in this dataset. **Copy and paste the code below to create DataFrames for the project summary and for the control samples with the associated batch information**:

```{python}
#| label: create_ctrl_samples_df
# Read in proj_summary
proj_summary = pd.read_table("data/project-summary.txt", 
                             header=0, index_col=0)

# Create ctrl_samples dataframe
ctrl_samples = pd.DataFrame(
  data = {"date": ["01/13/2018", "03/15/2018",  "01/13/2018",
                   "09/20/2018","03/15/2018"]}, 
  index = ["sample3", "sample10", "sample8", 
           "sample4", "sample15"])
```

```{python}
#| label: tbl-proj_summary
#| tbl-cap: DataFrame of quality metric information for an RNA-seq dataset.
# View RNA-seq QC information
proj_summary 
```

```{python}
#| label: tbl-ctrl_samples
#| tbl-cap: DataFrame of control samples with associated batch information.
# View control batch information
ctrl_samples
```

11. How many of the `ctrl_samples` are also in the `proj_summary` dataframe? Use the `isin` operator to compare sample names.

```{python}
#| label: shared_ctrl_samples_proj_summary
# Number of shared samples between ctrl_samples and proj_summary
print(len(proj_summary.index[proj_summary.index.isin(ctrl_samples.index)]))
print(len(ctrl_samples.index[ctrl_samples.index.isin(proj_summary.index)]))
```

12. Keep only the rows in `proj_summary` which correspond to those in `ctrl_samples`. Do this with the `isin` operator. Save it to a variable called `proj_summary_ctrl`.

```{python}
#| label: subset_proj_summary_by_ctrl_samples
# Subset proj_summary by the samples within ctrl_samples
proj_summary_ctrl = proj_summary[proj_summary.index.isin(ctrl_samples.index)]

# Print out proj_summary_ctrl
proj_summary_ctrl
```


13. Use `merge()` to add a column called `batch` to the `proj_summary_ctrl` dataframe. Assign this new dataframe back to `proj_summary_ctrl`.

```{python}
#| label: add_batch_information
# Using the match, add the batch information
proj_summary_ctrl = pd.merge(proj_summary_ctrl, 
                             ctrl_samples, 
                             left_index=True, 
                             right_index=True)

# Print proj_summary_ctrl
proj_summary_ctrl
```
