---
title: "Heatmaps"
description: |
  Write a description of the lesson here. 
author:
  - Noor Sohail
  - Will Gammerdinger
date: "2026-03-14"
categories: 
  - category_1
  - category_2
  - category_3
  - category_4
keywords:
  - keyword_1
  - keyword_2
  - keyword_3
  - keyword_4
  - keyword_5
  - keyword_6
license: "CC-BY-4.0"
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
#| label: load_libraries_data
#| echo: false
# Load libraries and data
# Interfacing with R quarto and python futzing
library(reticulate)
use_condaenv("/opt/anaconda3/envs/intro_python", required = TRUE)
```


Approximate time: XX minutes

## Learning Objectives 

In this lesson, we will:

- Learning Objective 1
- Learning Objective 2
- Learning Objective 3

## Overview of lesson

When doing XYZ...

## Heatmaps

```{python}
#| label: load_heatmap_data
# Load the data for heatmaps
import pandas as pd
rpkm_ordered = pd.read_csv("data/ordered_counts_rpkm.csv", index_col=0)
rpkm_ordered.head()
```

First let us identify the top 6 most highly expressed genes across all of our samples. We can do this by calculating the average expression for each gene across all samples and then selecting the top 6 genes with the highest average expression:

```{python}
#| label: top_genes
# Calculate the average expression for each gene across all samples
gene_means = rpkm_ordered.mean(axis=1)

# Get the top 6 most highly expressed genes
important_genes = gene_means.sort_values(ascending=False).head(6).index
important_genes
```

We can plot the gene expression for each of these genes across all of the samples using a heatmap. A heatmap is a graphical representation of data where individual values are represented as colors. In this case, we can use a heatmap to visualize the expression levels of our important genes across all of our samples.

```{python}
#| label: fig-top_genes_heatmap
#| fig-cap: "Heatmap of the RPKM values for the top 6 most highly expressed genes across all samples."
# Plot a heatmap of the important genes across all samples
import seaborn as sns
import matplotlib.pyplot as plt

# Subset the data to include only the important genes
important_genes_data = rpkm_ordered.loc[important_genes]

# Create the heatmap
sns.clustermap(important_genes_data, 
            cmap="viridis", z_score=0)

```

But we have no idea which samples are which in this heatmap! We can add some extra information to our heatmap by adding a color bar that indicates the `age` of the mouse for each sample. To do this, we need to load in our metadata data frame that contains the age information for each sample:

```{python}
#| label: load_metadata
# Load the metadata data frame
new_metadata = pd.read_csv("data/new_metadata.csv", index_col=0)
new_metadata.head()
```

Now we can add a color bar to our heatmap that indicates the age of the mouse for each sample:

```{python}
#| label: fig-top_genes_heatmap_age
#| fig-cap: "Heatmap of the RPKM values for the top 6 most highly expressed genes across all samples with a color bar indicating the age of the mouse for each sample."
# Create the heatmap with a color bar indicating the age of the mouse for each sample
sns.clustermap(important_genes_data, 
            cmap="viridis", z_score=0,
            col_colors=new_metadata["age_in_days"].map({3: "blue", 18: "orange"}))
``` 


### Subsection 1A

### Subsection 1B

:::{.callout-tip}
# [**Exercise 1**](13_lesson-Answer_key.qmd#exercise-1)
1. A question to evaluate Learning Objective 1
2. A followup question to question #1
3. ...
:::

## Topic 2

### Subsection 2A

### Subsection 2B

:::{.callout-tip}
# [**Exercise 2**](13_lesson-Answer_key.qmd#exercise-2)
1. A question to evaluate Learning Objective 2
2. A followup question to question #1
3. ...
:::

## Topic 3

### Subsection 3A

### Subsection 3B

:::{.callout-tip}
# [**Exercise 3**](13_lesson-Answer_key.qmd#exercise-3)
1. A question to evaluate Learning Objective 3
2. A followup question to question #1
3. ...
:::

***

[Back to Schedule](../schedule/schedule.qmd)