---
title: "Lesson 15"
description: |
  Write a description of the lesson here. 
author:
  - author_1
  - author_2
date: "YYYY-MM-DD"
categories: 
  - category_1
  - category_2
  - category_3
  - category_4
keywords:
  - keyword_1
  - keyword_2
  - keyword_3
  - keyword_4
  - keyword_5
  - keyword_6
license: "CC-BY-4.0"
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
#| label: load_libraries_data
#| echo: false
# Load libraries and data

```

Approximate time: XX minutes

## Learning Objectives 

In this lesson, we will:

- Learning Objective 1
- Learning Objective 2
- Learning Objective 3

## Overview of lesson

When doing XYZ...

## Topic 1

### Subsection 1A

### Subsection 1B

:::{.callout-tip}
# [**Exercise 1**](15_lesson-Answer_key.qmd#exercise-1)
1. A question to evaluate Learning Objective 1
2. A followup question to question #1
3. ...
:::

## Topic 2

### Subsection 2A

### Subsection 2B

:::{.callout-tip}
# [**Exercise 2**](15_lesson-Answer_key.qmd#exercise-2)
1. A question to evaluate Learning Objective 2
2. A followup question to question #1
3. ...
:::

## Topic 3

### Subsection 3A

### Subsection 3B

:::{.callout-tip}
# [**Exercise 3**](15_lesson-Answer_key.qmd#exercise-3)
1. A question to evaluate Learning Objective 3
2. A followup question to question #1
3. ...
:::

***

[Next Lesson >>](16_lesson.qmd)

[Back to Schedule](../schedule/schedule.qmd)

***

*These materials have been developed by members of the teaching team at the [Harvard Chan Bioinformatics Core (HBC)](http://bioinformatics.sph.harvard.edu/). These are open access materials distributed under the terms of the [Creative Commons Attribution license](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0), which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.*