# Introduction to Python

## Learning Objectives

- Setup and install Python and Jupyter Lab
- Write basic Python code and understand fundamental programming concepts
- Load and analyze data using Python libraries and functions
- Wrangle real-world datasets
- Create clear visualizations with `Matplotlib` and `Seaborn`
- Train a simple machine learning model using `scikit-learn`

## Installations

Download the most recent version of the **Graphical Installer** of Anaconda, Anaconda Navigator, for the appropriate operating system of your computer using the link below:

- [Anaconda](https://www.anaconda.com/download/success)

Once downloaded, run the installer and follow the prompts to complete the installation. The **default settings** should work for most users, but you can customize the installation if needed. This will install a new program called Anaconda Navigator.

## Lessons

- [Introduction to Python and Jupyter Lab](../lessons/01_setting_up.qmd)
- [Variables](../lessons/02_variables.qmd)
- [Conditional Statements](../lessons/03_conditional_statements.qmd)
- [Data Structures](../lessons/04_data_structures.qmd)
- [Loops](../lessons/05_loops.qmd)
- [Functions](../lessons/06_functions.qmd)
- [Libraries](../lessons/07_libraries.qmd)
- [Numpy Arrays](../lessons/08_numpy_arrays.qmd)
- [Pandas DataFrames](../lessons/09_pandas_dataframes.qmd)
- [Data Wrangling](../lessons/10_data_wrangling.qmd)
- [Plotting Basics](../lessons/11_plotting_basics.qmd)
- [Boxplots](../lessons/12_boxplots.qmd)
- [Machine Learning - Random Forest](../lessons/13_machine_learning.qmd)


## Resources

### Popular package resources

For a brief overview, or cheat sheet, of the most commonly used Python packages in data analysis, check out the following resources:

- [Pandas cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)
- [NumPy cheat sheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)
- [Matplotlib cheat sheet](https://matplotlib.org/cheatsheets/cheatsheets.pdf)
- [Scikit-learn cheat sheet](https://www.datacamp.com/cheat-sheet/scikit-learn-cheat-sheet-python-machine-learning)
- [Seaborn examples with code](https://seaborn.pydata.org/examples/index.html)


### Other Python courses

We acknowledge that there are many other groups that have created excellent Python courses:

- [Harvard CCB - Introduction to Data Analysis in Python](https://ccb-hms.github.io/workbench-python-workshop/index.html)
- [Google - Python Class](https://developers.google.com/edu/python)
- [Coursera - Python for Everybody](https://www.coursera.org/specializations/python)


### Learning more AI and ML

Python is one of the most popular languages for machine learning and artificial intelligence. If you are interested in learning more about these topics, we recommend the following resources as good starting points:

- [Coursera - Machine Learning by Andrew Ng](https://www.coursera.org/learn/machine-learning)
- [fast.ai - Practical Deep Learning for Coders](https://course.fast.ai/)


### Datasets for more practice

There are many websites that aggregate interesting datasets that you can use to practice your Python skills. Here are a few popular ones:

- [kaggle](https://www.kaggle.com/datasets)
- [Hugging Face](https://huggingface.co/datasets)